### ISSUE TITLE
Can't perform NumPy functions on data read by io.py

### ISSUE THREAD

**Issue by KaoruNishikawa** [nanten2/NASCO-analysis#67]
Since tp-data read by `io.py` keeps structured array attributes, NumPy functions (e.g. `np.mean()` or `data.mean('t')`) nor data specification (e.g. `data['timestamp']`) can't be performed on the returned xr.DataArray object.

**Comment by r-yamada1998** [comment]
Ok, I'll check and fix the bug. Thank you for your report.
